- application/modules/g/controllers/AuthController.php
- library/Garp/Model/Behavior/Translatable.php
- library/Garp/Model/Db/User.php
> Feature/yecommunity changes (delete)

- library/Garp/Content/Manager.php
Content Manager did not respect the `bidirectional` option for HABTM
homophyllic relationships.
@aapit Want to do a quick sanity check? 
Sorry for whitespace diffs, apparently this file still contained lines with trailing whitespace...
The meat of the pull request is in `_addHasAndBelongsToManyClause`.
This fixes Melkweg support #246
> Tweaked edge-case for homophile relations

- deploy/garp3.cap
- deploy/tasks/auth.cap
> added seperate deploy task for public cache permission

- library/Garp/Mailer.php
to make it work from a cli command
@harmenjanssen Maar omdat ik niet helemaal goed begrijp waarom de vorige versie niet goed werkt vanuit de cli. Niet zomaar mergen! Het lijkt te werken, maar ik wil weten waarom de vorige versie niet werkt. Tests blijven wel groen.
> change the way we get a view object from garp app

- application/modules/g/views/helpers/Snippet.php
Because sometimes you want to get a snippet in a specific language, not just the current language.
> added locale parameter to snippet view helper

- composer.json
- composer.lock
Locked tedivm/jshrink dependency to 1.1.0 due to new PHP version requirements.
> Locked tedivm/jshrink dependency to 1.1.0

- library/Garp/Model/Behavior/HtmlFilterable.php
- tests/library/Garp/Model/Behavior/HtmlFilterableTest.php
And enable iframe in a figure element
> disable Tidy because of issues with HTML5 elements

- composer.json
- composer.lock
- Locked phpdotenv
- Changed stablity to stable
- Made zendframework1 version a bit more specific
- Moved faker to require-dev and imported the dev version, since master is way out of sync, and we use some of those classes
- Added PHP to dependencies
> Minimum stability in Composer

- composer.json
- composer.lock
Hopefully this will allow `fzaninotto/faker` to be installed.
> Replaced stable minimum with prefer-stable

- .travis.yml
- library/Garp/Content/Manager.php
> Sets cmscontext property on bindingmodel

- scripts/garp.php
Fixes https://github.com/grrr-amsterdam/garp3/issues/69
> Fixed STDIN stream for CLI commands

- .gitignore
- library/Garp/Spawn/MySql/Manager.php
Just a minor tweak to save me a keypress :)
> Prevent unnecessary password prompt during spawn

- library/Garp/Content/Export/Csv.php
- library/Garp/Content/Export/Txt.php
- public/js/garp.exportwindow.js
Bugfix door Peter (heeft geen schrijfrechten voor garp3 repo)
> Fix sentry export ONDERWIJS-SUBSIDIES-7N

- application/functions.php
> Create model() function

- application/data/i18n/nl.php
- library/Garp/Auth/Adapter/Passwordless.php
- Add Zend Mail Validator
- Add Dutch i18n locales
AC-549
> Add email validation for Auth/Passwordless

- library/Garp/Cli/Command/PostcodeNl.php
> Make sure postcode.nl import only deletes its own records

- library/Garp/Model/Behavior/Nullable.php
- library/Garp/Spawn/Behavior/Set.php
- library/Garp/Spawn/Behavior/Type/Nullable.php
> Add default Nullable behavior

- application/init.php
- For testing of availability of the server I've used `Memcached::getVersion()`, which returns an array of servers with their version. If no server responds, the array will be empty.
- Tested on an actual project, and caching seems to be working properly again.
> Add memcached/libmemcached as memcached caching method

- library/Garp/Model/Db.php
- library/Garp/Test/PHPUnit/Helper.php
- tests/library/Garp/Model/DbTest.php
Ten behoeve van https://github.com/grrr-amsterdam/subsidieportaal/pull/565
> Fix arrayToWhereClause when given NULL values

- library/Garp/Auth/Adapter/Passwordless.php
> Fix getExpirationDate

- composer.json
- composer.lock
Er zat een typo in m'n commit message en ondertussen was er een andere hotfix tussen gekomen. Deze heb ik even gerebased.
> Update composer packages and especially dompdf

- library/Garp/Db/Table/Row.php
Kun jij een sanity check doen, Martijn? 
Eerste commit bevat louter style tweaks om PHPCS blij te maken.
> Garp row improvements

- library/Garp/Util/FullUrl.php
- library/Garp/Util/RoutedUrl.php
- tests/library/Garp/Util/FullUrlTest.php
- tests/library/Garp/Util/RoutedUrlTest.php
Gelijk maar even toegepast, die interface, zodat we die Url objecten ook kunnen gebruiken in Json output. 👌
> Make Url objects JsonSerializable

- CHANGELOG.md
- application/modules/g/views/layouts/admin-layout.phtml
- application/modules/g/views/layouts/admin-layout.twig
- deploy/tasks/assets.cap
It's backward-compatible even!
> Optional asset distribution

- application/configs/deploy.rb
- deploy/tasks/environment.cap
Disable verify_production_deploy question
**Todo** update [documentation](https://github.com/grrr-amsterdam/garp3/wiki/deployment)
> Add interactive mode to disable Cap questions

- public/js/extux/ext.ux.form.ckeditor.js
The problem with CKEditor seems to be that it loads asynchronous and computes width value on its own (not relying on the Ext Framework). This commit resizes the editor to the underlying Ext containers width upon rendering and resizing.
> Fix: CKEditor rendered too wide issue resolved

- library/Garp/Db/Table/Rowset.php
- tests/library/Garp/Db/Table/RowsetTest.php
Had to do a little cleaning up as well, thanks to PHPCS.
Let me know what you think!
> Make Rowset a Semigroup

- composer.json
- composer.lock
Prevents a require statement when an application wants to extends a G_
class.
> Autoload G_ classes

- composer.json
Ik wil Garp\Functional upgraden in Subsidieportaal, daarvoor is dit nodig.
> Update Composer to get latest Garp\Functional
