grrr-amsterdam/garp3

- library/Garp/Content/Manager.php
convert nativeColumns to lowercase due to problem with camelcased model configuration
Het gaat om de code op regel 443 t/m 450. Fastned gaf een error als ik het cms bij het Page model probeerde te zoeken.
Dit kwam omdat in de Page model config het volgende veld in camelcase is opgegeven.
"pageTitle": {
"multilingual": true,
"maxLength": 100,
"info": "Bepaalt de titel van de pagina, zichtbaar in de browsertab. Let op, werkt niet voor custom pagina's. Voor deze pagina's zijn snippets.",
"required": false
},
> convert nativeColumns to lowercase due to problem with camelcased model

- application/modules/g/controllers/ErrorController.php
- library/Garp/Service/Sentry.php
* Added a simple wrapper for Sentry, an exception monitoring service
* Added hook in Garp error controller, only firing on live sites and when `$ravenClient` is configured in `public/index.php`. This means that projects that do not have Sentry configured (yet) should not be influenced by this update.
The reason for this global configuration in `public/index.php` is that any errors should be logged in a very early stage, even before Garp has completely initialized. This should guarantee that even low level errors won't slip by unnoticed.
> Added Sentry service and implemented in Garp error hook

- library/Garp/Controller/Helper/Cache.php
Most OS'es have filename length limits and some requests may push beyond
this limit, which throws an exception.
This change tries to prevent that.
This hopefully fixes https://app.getsentry.com/grrr/melkweg/issues/151361081/
> Tests filename length before static caching

- deploy/garp3.cap
- deploy/tasks/garp.cap
- library/Garp/Cli/Command/Slack.php
Sends a Slack notification after deploy.
See channel `#harmens_test` for an example message.
> Send a Slack notification after deploy

- public/js/garp.passwordfieldset.js
Chrome 53 (might've been earlier) prevents loading of any data in the User model view when there's a stored password for the current website/admin. What I've done:
- Changed password input type to text, so effectively making the password plaintext by default. WordPress for example does this for a while now; there is no option to 'hide' your password from the screen while changing it, making any confirmation unnecessary (we didn't have that anyway).
- Removed the `plaintext` and `showpassword` field/button, since the default password is already plaintext.
- It's still accessible as a 'password', since the label says so.
PS: I think obfuscating your password while changing it is less important than showing your password while changing it (without any confirmation). Also a working CMS is …
> Made password field plaintext by default

- application/modules/g/controllers/ExtController.php
Why is this commented-out? It prevents support for the "[X-Content-Type-Options: nosniff](https://blog.mozilla.org/security/2016/08/26/mitigating-mime-confusion-attacks-in-firefox/)" header.
> re-added correct Content-Type

- library/Garp/Content/Cdn/Distributor.php
So that it's more suitable for batch processing and auto-deploy.
I took out the (broken) implementation of the Garp progress bar.
It's not suitable for machine processing, Travis hangs on it when trying to distribute the assets.
I replaced it by a dot line indicator. Takes a bit more space and gives less intuitive feedback on the process, but at least you can clearly see if the process is still running.
> Simplified display of CDN Distribute

- deploy/garp3.cap
- deploy/tasks/assets.cap
* Now gulping from within Capistrano process
* Copying `rev-manifest` json files from local to webserver
* Copying built css assets from local to webserver
* Distributing assets from within Capistrano process
I have moved the frontend build process and the distribution of assets to the Capistrano deploy process. This way, all that the new root `deploy.sh` file has to do is install dependencies, and then call on Capistrano. The building and distribution process are also tied together more to the deploy process in this fashion, as I think they should be.
If we implement this into the main branch, we can take the `rev-manifest` and the built css folder out of Git. We should also implement a `Gemfile` for existing dependencies which have so far been undefined. I am working on that in our test …
> Auto deploy

- deploy/tasks/auth.cap
Please, NEVER, NEVER use 777.
Only owner + group are allowed to have write permissions.
(Next to the fact that 777 is just an oldschool 'hackish' way of spelling out the permissions)
> Fixed 777 permissions

- application/init.php
Right now, `index.php` is the sole entrypoint which configures Sentry,
but it's not the only entrypoint of a Garp application.
CLI commands actually use `garp/scripts/garp.php`. Both of these use
`init.php` to configure a bunch of stuff, so that should be the place
where things like Sentry are configured.
Thus: this refactors `init.php` so that it tries to get Sentry's API
URL first from `getenv()`, allowing users to maintain Sentry's API URL
from a `.env` file.
To maintain backward compatibility it will still check for the existence
of the constant as before.
> Read Sentry API URL from .env before constant

- library/Garp/Model/Behavior/YouTubeable.php
- Durations were never saved, and caused errors on certain MySQL/MariaDB setups
- Duration is converted from IS0 8601 to an integer in seconds
> Fixed incorrect YouTube duration

- deploy/garp3.cap
- Split up `updated` task in a regular and after hook
- The `enable_under_construction` task is only invoked before running the spawn task, since `composer_install` and `push_assets` can take a long time, and have nothing to do with preventing database CRUD operations, and therefore limiting website downtime
---
In practice websites can be unreachable for up to 2 minutes when deploying, depending on the time a Composer install (updated dependencies, network conditions) and the scp'ing of assets takes. 
Now we invoke all those tasks before, since they're unrelated to preventing 'damage' due to code/database changes. The `enable_under_construction` is only invoked just before spawning, when everything is in place to start the actual spawning. This should result in a downtime of about 10 …
> Improve deploy downtime

- application/modules/g/views/scripts/content/admin.twig
This drove me absolutely crazy.
> Fixed: CMS LANGUAGES array now properly contains keys per language

- deploy/tasks/assets.cap
Distributes to CDN without argument by default, only if you want to deploy with a full distribution the user has to specify a specific `since`, like so:
```
cap staging deploy since=forever
```
This will make deployments a LOT faster, and developers Happy™.
Of course the `since` argument is tied to `g cdn distribute`, so the argument could be renamed to something CDN-global-specific, although this is one seemed most familiar.
> Added Capistrano since argument for CDN distribution

- tests/TestHelper.php
The `BASE_PATH` was pointing to a level higher than it should from a Garp unit test context.
> Added BASE_PATH specifically for Garp unit test context

- scripts/garp.php
Oops. Blocking was removed for grabbing data piped into scripts/garp.php.
It shouldn't have been removed for regular prompts for STDIN.
This simple fix makes sure everything is back to normal.
> Fix actually waiting for STDIN when prompting

- library/Garp/Cache/Manager.php
@HammenWS Not sure if you're familiar with this option, but it's almost always what you want when using curl. 🙂 
When omitted, curl just prints the output of the HTTP command into whatever process it's currently executed from.
> Configure curl not to auto-print its output

- deploy/tasks/assets.cap
Should only add less than a second extra to a deploy when all assets are properly installed on the deployers machine, but will prevent a lot of broken environments (which happened quite often lately).
---
- Will prevent building assets with missing packages
- Removed obsolete Grunt check
> Added Yarn install before building frontend assets

- composer.json
Instead of a dev-dependency.
Because Garp_Test_PHPUnit_TestCase relies upon a certain phpunit this
cannot be a dev-dependency.
> Made phpunit a true dependency

- CHANGELOG.md
- deploy/tasks/assets.cap
- library/Garp/Cli/Command/Cdn.php
- scripts/garp.php
Pff, het was wat meer werk om het aan elkaar te lijmen dan ik hoopte. 
Maar `g cdn distribute` binnen Capistrano maakt nu gebruik van 12g om de credentials van de target environment op te halen.
Eén gotcha: ik heb een JSON gem nodig om de respons te parsen van `12g env list`. Daarmee kan ik dan weer kijken of het CDN als _read-only_ staat gemarkeerd en dan sla ik het distribueren over.
Maar zie dat er nu niet echt een plek is om Ruby dependencies te definiëren binnen Garp? 
Dat zou betekenen dat projecten die hier gebruik van maken _zelf_ die json gem op de kop moeten tikken. (en dat we dus een breaking change binnen Garp hebben en een versie omhoog moeten)
Wat zijn jullie ideeën daarover?
> Cdn distribute warning

- deploy/tasks/garp.cap
> `--tags`
> Instead of using only the annotated tags, use any tag found in refs/tags namespace. This option enables matching a lightweight (non-annotated) tag.
So we'll get `v1.52.1-11-gb4659a72` instead of `v1.50.2-137-gb4659a72` (last tag which wasn't empty)
> Allow empty tags as deployed version in Slack

- deploy/tasks/assets.cap
Since assets are scp'd from your local machine, we have to make sure we
generate base- and extended model files before uploading to get
consistent results.
> Add spawn call to Capistrano deploy task to ensure consistent models

- deploy/garp3.cap
- deploy/tasks/garp.cap
Capistrano doesn't run a command twice, so we invoke a custom function
> Invoke OPcache reset on the CLI during deploy with separate task

- application/init.php
- library/Garp/Service/Sentry.php
- Add environment and release to logged errors
- Initialize Sentry with those tags, instead of only using them when custom loggin (also know as 'never')
- Move additional custom log tags to proper structure (`extra` and `user`)
- Dropped `extensions`, since those would need to be convert to a string and don't much information anyway
---
This should add `environment` and `release` to Sentry error logging, since that's now missing from Garp projects. Most errors are exceptions, which aren't triggered as a custom logged error. So initializing Sentry with those variables should send them along in all situations.
PS: would like to add `garp_version` in the future, but it's now part of `Garp_Service_Sentry`, and `Garp_Version` is already taken by the 'release version'.
> Update Sentry tags

- scripts/garp.php
`posix_isatty` can be used to determine wether data is being piped into a
script.
Using this, we can revert `stream_set_blocking()` to `true`, in order to
make the script wait for all input.
Specifically fixes a case where remote data (which takes a while to be
downloaded) from `12g` was not being picked up by `garp.php`.
> Check for interactivity before reading STDIN

- library/Garp/Model/Db/Snippet.php
This way it can be turned off in testing environment, making testing
setup simpler.
> Allow the "crash early" behavior of snippets to be configured

- docker-garp3.yml
We no longer expose default Docker ports. This prevents conflicts with any running services like web server or database on the host system.
> Remove default exposed Docker ports

- library/Garp/Model/Db/Faker.php
- Check for substrings rather than full matches, to pick up columns
where first/last names are prefixed or suffixed.
- Also, pick up on Dutch column names.
@HammenWS This fixes the Subsidieportaal problems where the fake name data would get truncated.
> Improve detection of name fields

- tests/library/Garp/Model/Validator/NotEmptyTest.php
Bij deze. Wegens gebrek aan return value ook maar `assertNull()` eromheen, analoog aan de andere tests.
> Add unittest to validate string("0") values

- library/Garp/Db/Table/Row.php
- tests/library/Garp/Db/Table/RowTest.php
This avoids the "The specified Table does not have the same columns as
the Row" exception thrown when the query result is a partial row.
> Test __wakeup and add more guards

- scripts/garp.php
The current check won't allow any other argument starting with an 'e'.
It's unbelievable it took us all these years before ever encountering
this problem.
> Fix checking for --e argument

- CHANGELOG.md
- composer.json
- composer.lock
Only Faker was a dev version, but [not a lot of changes](https://github.com/fzaninotto/Faker/compare/v1.8.0...76b1c25) between the current master and `v1.8.0`. 
Beside that `minimum-stability` and `prefer-stable` more or less eliminate each other.
> Use stable Composer packages

- .travis.yml
- deploy/tasks/assets.cap
`rsync` only transfers changes so it's much faster than `scp` especially when the assets didn't change.
`rsync` creates folders so `mkdir` becomes useless.
> Replace scp for rsync for faster assets distribution

- public/js/overrides.js
This fixes a long standing CMS issue for Firefox users. Keyboard navigation (mainly `up` and `down` arrow keys) didn't work anymore.
N.B. This fix is tested on Firefox, Chrome and Safari.
> Fix: GridPanel keyboard navigation for Firefox CMS users.

- docker-garp3.yml
`restart` is useful for orchestration, but not for local development. By removing this line the service won't restart automatically.
> Remove `restart: always` from garp_db

- library/Garp/Content/Export/Excel.php
Autosizing the column width in excel exports is not essential, slows the process down a lot and most importantly, relies on a function in PhpExcel that assumes casting a float to a string will put a `.` as a decimal point, which is not true if the server has for example a Dutch locale, therefor breaking the export.
> Remove auto sizing column width excel export

- library/Garp/Content/Export/Csv.php
Values that get exported to csv could be strings that correspond to functions, e.g. `dir`. This leads to unpredictable behavior of the exporter as `prop_set` also allows callable functions. By using map in this way, the function gets simpler and is freed from the unpredictability.
> Fix for dynamic values in csv exporter

- library/Garp/Content/Manager.php
`Zend_Db_Table_Rowset_Abstract::toArray` only works after one iteration. By calling `toArray` later in `Garp_Content_Manager` the first iteration is already done. `toArray` will be called on the row objects instead of directly returning the array from the database. Logic added to `init` inside the row object will be executed.
> Prevent bypassing row object

- CHANGELOG.md
- application/init.php
- composer.json
- composer.lock
- library/Garp/Service/Sentry.php
Note: `php_version` is no longer passed as a tag, because you get it for free from the Sentry SDK.
> Upgrade Sentry to version 2

- application/modules/g/controllers/RestController.php
- library/Garp/Cli/Command/Models.php
- library/Garp/Content/Api/Rest.php
- library/Garp/Content/Api/Rest/Schema.php
Change API `Content-Type` from default `text/html` to `application/json`.
Removed some usage of removed functions.
> Set API content-type to JSON

- application/modules/g/views/scripts/spawn/js/base_model.phtml
- library/Garp/Spawn/Field.php
This enables authors to manually enable or disable the searchable
property used in the CMS. By default, only text columns get searchable:
true, but by specifying `searchable: true` in the model config, any
column becomes searchable.
The reverse is possible as well: any text column configured with
`searchable: false` will stop being searchable.
> Allow option searchable in model configuration

- CHANGELOG.md
- application/removed-functions.php
Some changes to make upgrading Garp3 apps without Laravel from `v3.18` to `v3.19` more easy.
> Restore partial, snippet and __ in removed-functions.php

- composer.json
- phpunit.xml
To prevent conflicts with project who want to use PHPUnit 7 I've changed the version constraint. No BC changes between PHPUnit 6 or 7 that affect Garp.
Another option (see e076d49) is to remove PHPUnit as a dependency and add it as a suggestion. I ditched that change because `Garp_Test_PHPUnit_TestCase` extends PHPUnit which makes PHPUnit a library requirement.
> PHPUnit 7 compatibility

- library/Garp/Validate/Duration.php
- tests/library/Garp/Validate/DurationTest.php
`Warning: A non-numeric value encountered in /var/www/html/vendor/grrr-amsterdam/garp3/library/Garp/Validate/Duration.php on line 24`
On the break of Hacktoberfest ;-)
> Prevent warning when duration validator gets non numeric input

- library/Garp/Db/Table/Rowset.php
Sometimes we want to extend the rowset to allow some logic on a collection of rows. Because the filter functions etc. used to return instances of the self, the return rowsets would be of Garp_Db_Table_Rowset instead of whatever type of rowset the function was called. This is now fixed by returning instances of static.
Btw, `Garp_Db_Table_Rowset::concat` doet nu een check op `instanceof self`. Dit lijkt mij eigenlijk niet afdoende. Stel, we hebben twee rowsets, die niet extended zijn en dus instance zijn van `Garp_Db_Table_Rowset`, maar bevatten wel verschillende data, ze komen uit een andere table, kunnen die nu wel concat worden. Dat lijkt me niet helemaal juist. Beter wordt hier gecheckt op of ze dezelfde `tableClass` hebben.
> Make Rowset return instances of static to make it extendable

- library/Garp/Db/Table/Row.php
To have more control over the convertion of database data to object
values __set is used. With this change __set gets called during
construction of the row object.
> Use setFromArray to populate table row

- CHANGELOG.md
- library/Garp/Db/Table/Rowset.php
- tests/library/Garp/Db/Table/RowsetTest.php
For appending or prepending single rows to rowsets.
Same as `concat`, but when you have a single row. 
I've taken the names from `array_shift` and `array_push`, but now I'm doubting whether I shouldn't've just used `prepend` and `append`, what do you think?
> Add Rowset push and shift

- library/Garp/File/Storage/S3.php
This fixes CSV files being shown plainly in the browser instead of prompted for download.
(Fix for Subsidieportaal AC-1019)
> Add CSV mime-type to S3 storage

- composer.json
- library/Garp/Util/AssetUrl.php
- tests/library/Garp/Util/AssetUrlTest.php
`FullUrl` and `RoutedUrl` already implemented JsonSerializable, only `AssetUrl` didn't 😞
> Let AssetUrl implement JsonSerializable interface

- library/Garp/Content/Export/Abstract.php
The filter param is retrieved through $_GET (See: https://github.com/Shardj/zf1-future/blob/master/library/Zend/Controller/Request/Http.php\#L747-L764). This means the values are already urldecoded (See the warning at: https://www.php.net/urldecode). Since the filter strings are wrapped within % to provide wildcards for the query, urldecoding again here can lead to unexpected behavior, especially when a filter with a number is applied. Say we are searching for "21", the filter will be "%21%". Urldecoding this will lead to the string "!%". Which is not at all what we are searching for. And since the decoding is already applied, it can be removed here.
Nog een toevoeging: Gek genoeg is het lokaal niet te reproduceren. Als ik de decoded string uitprint zie ik idd dat het verkeerd gaat, maar …
> Remove breaking urldecoding on export filters

- CHANGELOG.md
- library/Garp/Spawn/Php/Model/Extended.php
- phpcs.xml
It's a fun feature but creates a git dependency that we can do without.
> Remove author information from extended models

- CHANGELOG.md
- library/Garp/Test/PHPUnit/TestCase.php
- library/Garp/Test/Traits/UsesTestHelper.php
- tests/application/modules/garp/views/helpers/AssetUrlTest.php
- tests/application/modules/garp/views/helpers/ImageHelperTest.php
- tests/library/Garp/Auth/Adapter/LinkedInTest.php
- tests/library/Garp/Auth/Adapter/PasswordlessTest.php
- tests/library/Garp/Db/Table/RowTest.php
- tests/library/Garp/File/Storage/LocalTest.php
- tests/library/Garp/FileTest.php
- tests/library/Garp/Model/Behavior/HtmlFilterableTest.php
- tests/library/Garp/Model/Db/FakerTest.php
- tests/library/Garp/Model/DbTest.php
- tests/library/Garp/Service/Elasticsearch/ConfigurationTest.php
- tests/library/Garp/Service/Elasticsearch/ModelTest.php
- tests/library/Garp/Service/Slack/ConfigTest.php
- tests/library/Garp/Spawn/Model/SetTest.php
- tests/library/Garp/Spawn/ModelTest.php
- tests/library/Garp/Spawn/MySql/TableTest.php
- tests/library/Garp/Spawn/Relation/SetTest.php
- tests/library/Garp/Util/AssetUrlTest.php
- tests/library/Garp/Util/FullUrlTest.php
- tests/library/Garp/VersionTest.php
This allows you to start extending other TestCase classes (like the one
from Laravel), while simultaneously keeping Garp functionality.
This hopefully eases the transition to another framework.
> Move Garp TestCase functionality to trait

- library/Garp/Test/Traits/UsesTestHelper.php
It cannot share a property with subclasses because subclasses will
always change the value, and this is invalid in PHP.
> Remove $_mockData from TestCase trait

- library/Garp/Spawn/Relation.php
Especially since it conflicts with the changes in 115c42c0 (in which
`column` is chosen as property for overriding the auto-generated foreign
key column).
> Remove seemingly useless mirrored property

- library/Garp/Cli/Command/Image.php
When scaling by filename the overwrite flag was ignored.
> Fix overwrite generate-scaled-image-filename
